### ISSUE TITLE
file.VideoGet 

### ISSUE THREAD

**Issue by liqkj** [bububa/oceanengine#10]
![image](https://user-images.githubusercontent.com/29451637/178218671-dae09c73-5da6-4b81-9056-94aa491ca8ad.png)

1.7.16版本后 获取视频连接 接口 内存指针问题

**Comment by bububa** [comment]
这不是库的问题吧，是不是调用时候没检查返回结果nil

**Comment by liqkj** [comment]
退回到 1.7.16  版本就正常了

**Comment by liqkj** [comment]
错误是 我检查err返回的 err有错误，结果已经不检查了

**Comment by liqkj** [comment]
<img width="641" alt="1657769893658" src="https://user-images.githubusercontent.com/29451637/178892869-b83a32d5-c3e3-41b7-a0b2-2a7207c3750f.png">
![1657769859060](https://user-images.githubusercontent.com/29451637/178892876-1cb94750-4476-469e-b726-578c12d817e8.jpg)

**Comment by bububa** [comment]
没发现你说的问题，你把用最新版本SDK调用代码和日志发我看看把。

测试代码
`golang
package main

import (
        "log"

        fileApi "github.com/bububa/oceanengine/marketing-api/api/file"
        "github.com/bububa/oceanengine/marketing-api/core"
        fileModel "github.com/bububa/oceanengine/marketing-api/model/file"
)

func main() {
        appID := "xxxxx"
        secret := "xxxxxx"
        accessToken := "xxxxx"
        clt := core.NewSDKClient(appID, secret)
        clt.SetDebug(true)
        req := fileModel.VideoGetRequest{
                AdvertiserID: 1738228919504909,
                Filtering: &fileModel.VideoGetFilter{
                        MaterialIDs: []uint64{7119094469987352579},
                },
        }
        ret, err := fileApi.VideoGet(clt, accessToken, &req)
        if err != nil {
                log.Fatalln(err)
        }
        log.Printf("%v\n", ret)
}

`

正确调用日志
`
2022/07/14 16:25:11 [DEBUG] [API] GET https://ad.oceanengine.com/open_api/2/file/video/get/?advertiser_id=1738228919504909&filtering=%7B%22material_ids%22%3A%5B7119094469987352579%5D%7D
2022/07/14 16:25:11 [DEBUG] [API] http response body:
{
    "code": 0,
    "message": "OK",
    "request_id": "202207141625110101502180451ED68443",
    "data": {
        "list": [
            {
                "duration": 35.605,
                "source": "ACCOUNT_PUSH",
                "filename": "\u63a8\u9001\u89c6\u9891_0711-\u5929\u5929\u6e05-\u51cf\u80a5-\u5fd7\u989604-2",
                "material_id": 7119094469987352579,
                "organization_tags": [],
                "id": "v03033g10000cb61lhjc77u3lbsbpovg",
                "format": "MOV",
                "poster_url": "http://p26-sign.douyinpic.com/tos-cn-p-0051/826ab380908d4c9fa5083eee73ae0a87~tplv-noop.image?x-expires=1657790746&x-signature=9zWNBnYAvciIHNTSsG6OMaQ1wo8%3D",
                "url": "http://v3-default.365yg.com/0da8e2b8eca3528196f892ed4b99ebbe/62cfe11a/video/tos/cn/tos-cn-ve-51-alinc2/ad1dbc51b0da46649d9df8a7ce279fb8/?a=0&ch=0&cr=0&dr=0&lr=ad&cd=0%7C0%7C1%7C0&cv=1&br=1744&bt=1744&cs=0&ds=3&ft=dlfYl--bz7ThW.N351t8Z&mime_type=video_mp4&qs=0&rc=NTtoNTlkNzk2NjM6ZDY7aEBpanJlZTY6Zms0ZTMzNDYzM0BjMWAuNjIvXzIxMl8wNmFeYSNzbXBpcjRnaTNgLS1kMDBzcw%3D%3D&l=202207141625110101502180451ED68443",
                "signature": "349156e7a0645ba9fcd4290ed818d44a",
                "create_time": "2022-07-13 22:35:18",
                "labels": [],
                "size": 48711405,
                "height": 1280,
                "bit_rate": 10944743,
                "width": 720
            }
        ],
        "page_info": {
            "total_page": 1,
            "page": 1,
            "total_number": 1,
            "page_size": 20
        }
    }
}
2022/07/14 16:25:11 &{[{v03033g10000cb61lhjc77u3lbsbpovg  48711405 720 1280 http://v3-default.365yg.com/0da8e2b8eca3528196f892ed4b99ebbe/62cfe11a/video/tos/cn/tos-cn-ve-51-alinc2/ad1dbc51b0da46649d9df8a7ce279fb8/?a=0&ch=0&cr=0&dr=0&lr=ad&cd=0%7C0%7C1%7C0&cv=1&br=1744&bt=1744&cs=0&ds=3&ft=dlfYl--bz7ThW.N351t8Z&mime_type=video_mp4&qs=0&rc=NTtoNTlkNzk2NjM6ZDY7aEBpanJlZTY6Zms0ZTMzNDYzM0BjMWAuNjIvXzIxMl8wNmFeYSNzbXBpcjRnaTNgLS1kMDBzcw%3D%3D&l=202207141625110101502180451ED68443  MOV 349156e7a0645ba9fcd4290ed818d44a http://p26-sign.douyinpic.com/tos-cn-p-0051/826ab380908d4c9fa5083eee73ae0a87~tplv-noop.image?x-expires=1657790746&x-signature=9zWNBnYAvciIHNTSsG6OMaQ1wo8%3D 10944743 35.605 7119094469987352579 ACCOUNT_PUSH 2022-07-13 22:35:18 推送视频_0711-天天清-减肥-志颖04-2 [] 0  0}] 0xc0000183c0}
`

错误调用日志
`
2022/07/14 16:28:22 [DEBUG] [API] GET https://ad.oceanengine.com/open_api/2/file/video/get/?advertiser_id=1738228919504909&filtering=%7B%22material_ids%22%3A%5B7119094469987352579%5D%7D
2022/07/14 16:28:22 [DEBUG] [API] http response body:
{
    "code": 40105,
    "message": "Access token is invalid, when you call access_token or refresh_token api, old token will become invalid.",
    "request_id": "2022071416282201020810513214752590"
}
2022/07/14 16:28:22 40105:Access token is invalid, when you call access_token or refresh_token api, old token will become invalid.
exit status 1
`

**Comment by liqkj** [comment]
找到原因了，是我没有看新版的使用方式，以前版本  core.SDKClient 这个对象无需设置，新版是必须设置导致的原因
