### ISSUE TITLE
获取落地页组时 类型错误

### ISSUE THREAD

**Issue by huangxz1120** [bububa/oceanengine#24]
代码里面现在使用的是通用分页类型结构体, 总item个数结果类型为int64
![image](https://user-images.githubusercontent.com/46680003/218406604-97e8033d-877a-4048-b36f-f62e106ebbef.png)
但是数据返回的是string类型
![image](https://user-images.githubusercontent.com/46680003/218406777-db0acc75-a1c8-49c5-afe1-983ca4b0e134.png)

**Comment by huangxz1120** [comment]
> 总item个数结果类型为

接口为 github.com/bububa/oceanengine/marketing-api/api/tools/landinggroup  的get方法

**Comment by bububa** [comment]
能用 model/types 里的 model.Int64 吗

**Comment by huangxz1120** [comment]
> 能用 model/types 里的 model.Int64 吗

返回接口的total_number的类型是string 类型,代码里面通用翻页类型的total_number是int64, 在使用json转为结构体时会报类型错误
![image](https://user-images.githubusercontent.com/46680003/218629358-1e3e935c-c607-4ed5-8c5b-1bd9550221d0.png)
问题原因是类型不匹配
