### ISSUE TITLE
结构体有误

### ISSUE THREAD

**Issue by 594872799** [bububa/oceanengine#44]
vendor/github.com/bububa/oceanengine/marketing-api/model/report/v3/dimensions.go
下的
CustomDimensions.StatTimeWeek这个结构体的字段为什么是int类型？Unmarshal的时候报错了

**Comment by bububa** [comment]
pull request吧

**Comment by 594872799** [comment]
对，发起get请求，获取报表数据的时候

**Comment by 594872799** [comment]
他返回的格式是 2023-06-25-2023-07-01 这样的

**Comment by 594872799** [comment]
他返回的值是这样的
"rows": [
            {
                "dimensions": {
                    "stat_time_week": "2023-05-31-2023-06-04"
                },
                "metrics": {
                    "active": "1",
                    "active_cost": "0.00",
                    "active_pay": "0",
                    "active_pay_cost": "0.00",
                    "active_pay_rate": "0.00",
                    "active_rate": "0.00",
                    "active_register": "0",
                    "active_register_cost": "0.00",
                    "active_register_rate": "0.00",
                    "click_cnt": "0",
                    "conversion_cost": "0.00",
                    "conversion_rate": "0.00",
                    "convert_cnt": "0",
                    "cpc_platform": "0.00",
                    "cpm_platform": "0.00",
                    "ctr": "0.00",
                    "game_addiction": "0",
                    "game_addiction_cost": "0.00",
                    "game_addiction_rate": "0.00",
                    "in_app_order": "0",
                    "show_cnt": "0",
                    "stat_cost": "0.00"
                }
            }
        ]

**Comment by 594872799** [comment]
![image](https://github.com/bububa/oceanengine/assets/35714881/b36a3a2e-435e-429b-983f-a7b7cf08d228)
请求
