### ISSUE TITLE
API Response 结构体 json tag 是否有必要加上 omitempty

### ISSUE THREAD

**Issue by hldh214** [bububa/oceanengine#5]
比如

https://github.com/bububa/oceanengine/blob/d060e741dfd616a6fbe10a589bb3d1d79781460e/marketing-api/model/qianchuan/product/product.go#L14

若接口里的 `product_rate` 返回 `0`, 序列化的时候就会忽略掉这个字段
或者把所有结构体成员类型都改为指针类型, 也能避免这个问题, 比如广点通就是这么干的

https://github.com/TencentAd/marketing-api-go-sdk/blob/114772d76c5b8813498777a757fb9ce39f047d9c/pkg/model/model_ads_update_response_data.go#L13

不知道大家有啥想法

**Comment by bububa** [comment]
广点通把所有成员都变成指针有很大问题，明显是个偷懒的方案，1. 会增加gc压力; 2. 使用非常不方便；3. 很容易出现循环内指针误用或可变性问题造成使用错误。
int/float/string类型成员作为指针序列化仅在更新或新建接口时有意义，巨量大部分新建或更新接口都不是传递的内嵌结构体，可以指针对更新和新建类接口参数对需要的字段设置指针或去掉omitempty

**Comment by bububa** [comment]
我觉得这个在前端判断好一些
