### ISSUE TITLE
查询抖音帐号和类目信息接口BUG

### ISSUE THREAD

**Issue by openthe88** [bububa/oceanengine#58]
![image](https://github.com/bububa/oceanengine/assets/16093534/d780ffec-3c63-4396-8df3-61ae9ab4aa85)
![image](https://github.com/bububa/oceanengine/assets/16093534/bde98980-b7fc-4686-9036-e72a48e984ca)

头条返回结构体实际上在list字段是数组, 所以结构体应该也为数组

<img width="1400" alt="image" src="https://github.com/bububa/oceanengine/assets/16093534/64a93504-730c-4e8a-9c39-c4698bdd1c41">
<img width="799" alt="image" src="https://github.com/bububa/oceanengine/assets/16093534/2b9f5d9b-a7b6-4aec-b048-840221777959">

如上修改加上数组结构才能正常, 因为不会pull requests 所以只能提issues给大佬进行BUG修复.

**Comment by bububa** [comment]
fixed v1.21.6
