### ISSUE TITLE
返回模型字段类型定义无法解析

### ISSUE THREAD

**Issue by hxhai** [bububa/oceanengine#66]
解析报错：json Decode failed: json: cannot unmarshal number into Go struct field Product.data.list.offline_time of type string

![image](https://github.com/bububa/oceanengine/assets/88771276/e8bbda9d-cf8b-451e-8c00-d36288d69ba3)
![image](https://github.com/bububa/oceanengine/assets/88771276/6270c022-2ae1-41e6-bbb7-dc1dd643f569)

**Comment by bububa** [comment]
try v1.25.4
